In [1]:
import numpy as np

In [3]:
np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

In [4]:
a = np.array([1,2,3])

In [5]:
print a

SyntaxError: Missing parentheses in call to 'print'. Did you mean print(a)? (<ipython-input-5-da1608c9d425>, line 1)

In [6]:
print (a)

[1 2 3]


In [7]:
b = np.array([[1,2],[3,4]])

In [8]:
print (b)

[[1 2]
 [3 4]]


In [9]:
c = np.array([1,2,3,4,5], ndmin=2)

In [10]:
print (c)

[[1 2 3 4 5]]


In [11]:
d = np.array([1,2,3], ndmin=5)

In [12]:
print(d)

[[[[[1 2 3]]]]]


In [13]:
co = np.array([1,2,3], dtype=complex)
print (co)

[1.+0.j 2.+0.j 3.+0.j]


In [14]:
dt = np.dtype('i4')
print (dt)

int32


In [ ]:
dt = np.dtype([('age', np.int8)])
a = np.array([])