In [4]:
import numpy as np

a_list = [1,2,3]
arr = np.array(a_list)

In [5]:
arr

array([1, 2, 3])

In [9]:
list_of_list = [a_list, a_list, a_list]
list_of_list

[[1, 2, 3], [1, 2, 3], [1, 2, 3]]

In [11]:
a_matrix = np.array(list_of_list)
a_matrix

array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [12]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros(2,3)

TypeError: data type not understood

In [17]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [19]:
#identity matrix

In [20]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [21]:
np.random.rand(5)

array([0.29456738, 0.40017807, 0.84098296, 0.22118036, 0.59561683])

In [22]:
np.random.rand(5,5)

array([[0.19272379, 0.16271631, 0.11143136, 0.7499985 , 0.2359051 ],
       [0.76241034, 0.19084733, 0.62956311, 0.42468891, 0.42050186],
       [0.96238284, 0.5669224 , 0.95016166, 0.52498222, 0.75615341],
       [0.00924832, 0.13485779, 0.68210561, 0.26298541, 0.98366494],
       [0.35467011, 0.53856067, 0.02465502, 0.38727057, 0.17145852]])

In [23]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])